on:
  pull_request:
  push:
    branches:
      - main
      - beta
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: JRMurr/direnv-nix-action@v4.1.0
      - run: "poetry run pytest"
  release:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.repository_owner == 'mirkolenz' && github.event_name == 'push' }}
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: JRMurr/direnv-nix-action@v4.1.0
      - uses: cihelper/action-semanticrelease-poetry@v1
        id: semanticrelease
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
      - uses: cihelper/action-docker-publish@v1
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
        with:
          version: ${{ steps.semanticrelease.outputs.version }}
          build-image: false
      - run: "nix run .#copyDockerImage"
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
